# Basic settings
title: IA Resources
description: "Une collection de ressources pour l'apprentissage et le développement d'outils IA"
author: EnderBenjy
baseurl: "/ia_ressources" # Repository name
url: "https://dupuisb.github.io" # Your GitHub Pages URL

# Enable the Cayman theme
remote_theme: pages-themes/cayman@v0.2.0

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-toc # Table of contents (TOC) generator
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-feed
  - jemoji # Emojis
  - jekyll-scholar # LaTeX support for citations and references
  - jekyll-katex # LaTeX support with KaTeX
  - jekyll-remote-theme

markdown: 
  math_engine: katex
highlighter: rouge

show_sidebar: true
show_excerpts: true

paginate: 10
paginate_path: "/page:num/"

