# Basic settings
title: IA Resources
description: "A collection of resources for AI research and development"
author: EnderBenjy
baseurl: "/ia_ressources" # Repository name
url: "https://dupuisb.github.io" # Your GitHub Pages URL

# Enable the Cayman theme
remote_theme: pages-themes/cayman@v0.2.0

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-toc # Table of contents (TOC) generator
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-feed
  - jemoji # Emojis in markdown
  - jekyll-scholar # LaTeX support for citations and references
  - jekyll-katex # LaTeX support with KaTeX
  - jekyll-remote-theme # add this line to the plugins list if you already have one

# Markdown settings
markdown: 
  math_engine: katex
highlighter: rouge

# Sidebar and navigation settings
show_sidebar: true
show_excerpts: true

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Customization options
# Modify these colors to customize the theme further
# Customize the theme's colors by uncommenting and setting these variables
# colors:
#   text: "#333333"
#   background: "#ffffff"
#   link: "#007bff"
#   sidebar: "#f4f4f4"